/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

/* Define if the compiler supports basic C++17 syntax */
#define HAVE_CXX17 1

/* Provides support for installation of resolvers from theTomahawk website */
#define HAVE_QT5 1

/* Whether to build with QT5 X11 support */
#define HAVE_X11 1

/* Define to the address where bug reports for thispackage should be sent. */
#define PACKAGE_BUGREPORT "https://github.com/p01arst0rm/libportfwd/issues"

/* Define to the full name of this package. */
#define PACKAGE_NAME "libportfwd"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "libportfwd 0.1.0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "libportfwd"

/* Define to the home page for this package. */
#define PACKAGE_URL "https://ever3st.com"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.1.0"

